services:
    auth:
        class: omni\eveapi\auth\auth_eveapi

    auth.provider.oauth.service.eveonline:
        class: omni\eveapi\auth\provider\oauth\service\eveonline
        arguments:
            - @config
            - @request
        tags:
            - { name: auth.provider.oauth.service }
