imports:
    - { resource: auth.yml }
    - { resource: avatar.yml }
    - { resource: profilefield.yml }

services:
    omni.eveapi.cron:
        class: omni\eveapi\controller\cron
        arguments:
            - @config
            - @controller.helper

    omni.eveapi.user:
        class: omni\eveapi\controller\user
        arguments:
            - @config
            - @controller.helper

    omni.eveapi.json:
        class: omni\eveapi\controller\json
        arguments:
            - @config
            - @controller.helper

    omni.eveapi.listener:
        class: omni\eveapi\event\main_listener
        arguments:
            - @config
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
